api:
  replicaCount: 1
  image:
    repository: an6eel/gitops-seminar-code
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 68fa98be212a082e96e39744cd73d756e3c5a3fe
  namespace: "preprod"
  serviceAccount:
    create: false
  podAnnotations: {}
  service:
    name: preprod-service
    port: 8000
  ingress:
    enabled: true
    hosts:
    - preprod.an6eel.name
    annotations:
      kubernetes.io/ingress.class: nginx
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    #targetMemoryUtilizationPercentage: 80
