api:
  replicaCount: 3
  image:
    repository: an6eel/gitops-seminar-code
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  namespace: "prod"
  serviceAccount:
    create: false
  podAnnotations: {}

  service:
    name: prod-service
    port: 8000
  ingress:
    enabled: true
    hosts:
    - an6eel.name
    annotations:
      kubernetes.io/ingress.class: nginx
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    #targetMemoryUtilizationPercentage: 80

