apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-api
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: gitops
  source:
    helm:
      valueFiles:
      - resources/apps/prometheus/values.yml
    path: charts/prometheus
    repoURL: https://github.com/an6eel/gitops-seminar-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
