apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  project: gitops
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: resources/apps/prometheus
    repoURL: https://github.com/an6eel/gitops-seminar-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true